### ISSUE TITLE
Recommended Thrive articles link and panel not showing

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/micro-frontends-challenges-app#10]
With the latest MFE challenge details page, it's not showing the `Recommended Thrive articles` link or panel on the challenge details screen.  The expectation is that the display of thrive articles *exactly* matches the existing site / page from the community app (https://github.com/topcoder-platform/community-app)

* Current:  https://platform.topcoder-dev.com/earn/find/challenges/af60c098-e5cf-4a7a-935a-c6a18417fa5c
* Existing: http://www.topcoder-dev.com/challenges/af60c098-e5cf-4a7a-935a-c6a18417fa5c

### Expected

<img width="1505" alt="Screen_Shot_2021-09-28_at_8_16_59_am" src="https://user-images.githubusercontent.com/21790/134992926-21944c35-ceb9-4d9a-9e61-82bf70674052.png">

<img width="1505" alt="Screen_Shot_2021-09-28_at_8_17_10_am" src="https://user-images.githubusercontent.com/21790/134992941-adeca627-9951-4624-a848-578df0d6fec8.png">

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1437" alt="Screenshot 2021-09-28 at 1 16 52 PM" src="https://user-images.githubusercontent.com/58783823/135045349-00d1ad57-0873-4b04-ac80-6d0234df8d65.png">
