### ISSUE TITLE
[$15] [Web- Chrome] App is not navigating challenge page 1 if user go to last page of the challenge and click challenge link menu

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/micro-frontends-challenges-app#109]
Summary :
[Web- Chrome] App is not navigating challenge page 1 if user go to last page of the challenge and click challenge link menu 

https://user-images.githubusercontent.com/42398485/142822117-d96a9c21-1645-41e2-8071-dc91b1f75b99.mp4

Steps to reproduce:
1.	Open the https://platform.topcoder.com/earn/find/challenges
2.	Go to last page 
3.	Click challenge Link menu

Actual:
App is not navigating challenge page 1 if user go to last page of the challenge and click challenge link menu

Expected:
App should navigate to challenge page 1 if user go to last page of the challenge and click challenge link menu

Environment:

_	Device(s): Windows 
_	Resolution: 1920_1080
_	Operating System: Windows 10
_	Browser(s): Chrome | Version 95.0.4638.54 (| Firefox 93.0 (64-bit)| Edge 95.0.1020.30

**Comment by fikzzzy** [comment]
@bug-bash-helper assign

**Comment by fikzzzy** [comment]
@bug-bash-helper https://github.com/topcoder-platform/micro-frontends-challenges-app/pull/163 is ready for review

**Comment by codejamtc** [comment]
Fixed :ok:

https://user-images.githubusercontent.com/42398485/142350951-e358c6b9-7e22-4037-b89e-bc58cdbfe861.mp4

**Comment by codejamtc** [comment]
@LieutenantRoger Please check this on latest dev env

https://user-images.githubusercontent.com/42398485/142822490-b33e432f-8330-4125-aca7-fe1c124ada05.mp4

**Comment by LieutenantRoger** [comment]
@codejamtc

This is expected behavior, we optimized this area by incorporating this PR:  https://github.com/topcoder-platform/micro-frontends-challenges-app/pull/153


So when a user clicked the challenge link, with it's current state not changed, the app will simply reload the challenges based on the current filters, reverting to page 1 seems not very good to me.

**Comment by codejamtc** [comment]
@LieutenantRoger Agree, we are good with this one too

**Comment by codejamtc** [comment]
Verified in Prod :ok:

https://user-images.githubusercontent.com/42398485/142980957-f533b1c5-9541-45e3-9816-dab919ea91f2.mp4
