### ISSUE TITLE
Clicking the userhandle in the challenge details page is directing to wrong url

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-challenges-app#12]
Description:

Clicking the userhandle displayed in the challenge details page is directing to wrong url (https://platform.topcoder-dev.com/members/lazybaer) instead of https://www.topcoder-dev.com/members/lazybaer

Please ensure the environment is used properly.  In dev, we should go to `topcoder-dev.com`, but in prod the root URL should be `topcoder.com`

https://user-images.githubusercontent.com/55895538/135026149-6eb3c530-1468-4472-894c-b44940175cf6.mp4

**Comment by SathyaJayabal** [comment]
Note: also includes user handles in the winners tab for completed challenges and registrants tab.

**Comment by SathyaJayabal** [comment]
@jmgasper , verified that the user handle points to the comm app member profile page. This should be good for our production release. 
<img width="1440" alt="Screenshot 2021-10-04 at 8 51 51 AM" src="https://user-images.githubusercontent.com/58783823/135788258-561863f8-20dd-418f-8b1e-cb1f5bb9f796.png">
