### ISSUE TITLE
Submission link

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/micro-frontends-challenges-app#17]
Currently, we're still working on the submission page functionality into the MFE.  For now, let's have the `Submit` link go *back* to the community app.

So, instead of:

https://platform.topcoder-dev.com/earn/find/challenges/d4b75f2d-1998-47cf-9c9d-69bcc2d4c474/submit

The link would go to

https://topcoder-dev.com/challenges/d4b75f2d-1998-47cf-9c9d-69bcc2d4c474/submit

**Comment by sandhiyakavi** [comment]
Verified on Dev Env


https://user-images.githubusercontent.com/55895538/135566510-e41a0922-26aa-4451-b10e-77d8b23fcbda.mp4
