### ISSUE TITLE
Closed challenges does not show winner on listing page, as they show on old closed challenge page

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/micro-frontends-challenges-app#225]
**Summary:**
Closed challenges does not show winner on listing page, as they show on old closed challenge page

**Steps to Reproduce:**

1. go to https://platform.topcoder.com/earn/find/challenges
2. click on 'closed challenges'

**Actual Result:**

Closed challenges does not show winner on listing page, as they show on old closed challenge page

**Expected Result:**

Should show the winner as in old challenge listing

**Environment Details:**

***Devices(s):***

Laptop

***Operating System:*** 

Windows 10

***Browser and Version:***

Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Screen recording or Screen snapshot:**
![2021-10-29_20-46-18](/uploads/f25dd48caee7236ca05b5af5814292a5/2021-10-29_20-46-18.mp4)

**Comment by LieutenantRoger** [comment]
Need Oanh to take a look, this looks like a feature request

**Comment by Oanh-and-only-Oanh** [comment]
out of scope
