### ISSUE TITLE
Buttons on the challenge page should follow the current TC GUI Kit

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/micro-frontends-challenges-app#238]
**Summary:**
Buttons on the challenge page should follow the current TC GUI Kit

**Steps to Reproduce:**

1. Open https://platform.topcoder.com/earn/find/challenges/6ca43e88-56a0-4150-9e99-a6bcea67e3b1
2. Observe the Registration and Submit buttons

**Actual Result:**
They are following the old style

**Expected Result:**
The buttons shoudl follow the current TC GUI Kit

**Environment Details:**

***Devices(s):***
MacBook Pro
***Operating System and version:***
MacOS Catalina
***Browser and version:***
Safari 14.0.3
**Screen recording or Screen snapshot:**
![Screenshot_2021-10-29_at_17.26.30](/uploads/314450accfc4733585f3baf034f13f39/Screenshot_2021-10-29_at_17.26.30.png)

**Comment by LieutenantRoger** [comment]
Need input from Oanh, Actually not sure what's the new TC GUI Kit style.

**Comment by Oanh-and-only-Oanh** [comment]
We will not address and UX issues.
