### ISSUE TITLE
Tabs on the challenge page should follow the current TC GUI Kit

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/micro-frontends-challenges-app#240]
**Summary:**
Tabs on the challenge page should follow the current TC GUI Kit

**Steps to Reproduce:**

1. Open https://platform.topcoder.com/earn/find/challenges/6ca43e88-56a0-4150-9e99-a6bcea67e3b1
2. Observe the tabs

**Actual Result:**
They are following the old style

**Expected Result:**
The tabs should follow the current TC GUI Kit

**Environment Details:**

***Devices(s):***
MacBook Pro
***Operating System and version:***
MacOS Catalina
***Browser and version:***
Safari 14.0.3
**Screen recording or Screen snapshot:**

![Screenshot_2021-10-29_at_17.28.35](/uploads/a05f9114e084cd96bc08442e38b97fe2/Screenshot_2021-10-29_at_17.28.35.png)

**Comment by Oanh-and-only-Oanh** [comment]
out of scope
