### ISSUE TITLE
Submit button is not enabled once we checked everything

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/micro-frontends-challenges-app#324]
Please refer to the snapshot: 

https://monosnap.com/file/szKt7dI1q151MWNHb54Y0qaX11AO3t

When we have uploaded a zip file, and checked the checkbox by clicking the label `I UNDERSTAND AND AGREE` (don't click the checkbox), the submit button still is not enabled

Right now, member can't submit a submission anymore.

**Comment by SathyaJayabal** [comment]
verified on dev

https://user-images.githubusercontent.com/58783823/152313976-96e14697-82ac-4d98-b515-f1effa723231.mov

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/152317845-045d6b1e-134d-450f-b0c2-57b6d3b554ff.mov
