### ISSUE TITLE
Filtering by the tags in the challenge details page is not working correctly

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-challenges-app#7]
Description:

Filtering by the tags in the challenge details page is not working correctly.

https://user-images.githubusercontent.com/55895538/134889645-f5933e06-aa4e-4048-9791-2924d34fd6c1.mp4

**Comment by SathyaJayabal** [comment]
Additionally, when a tag is selected from the challenge details page, the search url must be `tags[] = tag` instead of `search=tag`

See example:

https://user-images.githubusercontent.com/58783823/134891668-01aa13b9-e3d8-4615-9abd-294407b23382.mov

**Comment by SathyaJayabal** [comment]
@jmgasper the second comment is not addressed.
https://github.com/topcoder-platform/micro-frontends-challenges-app/issues/7#issuecomment-927734326

**Comment by jmgasper** [comment]
@SathyaJayabal - I think this is fixed now, please have a look.

**Comment by SathyaJayabal** [comment]
verified on dev

https://user-images.githubusercontent.com/58783823/135217535-d956ff4b-bec2-4446-b6ea-413091258905.mov
