### ISSUE TITLE
[Chrome] Doesn't have my challenges filter

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/micro-frontends-challenges-app#73]
**Steps to Reproduce**

Open the link [https://platform.topcoder.com/earn/find/challenges?bucket=Closed%20Challenges&endDateStart=2021-10-04T17:00:00.000Z&page=1&perPage=10&sortBy=updated&totalPrizesFrom=0&totalPrizesTo=10000&tracks[]=DES&tracks[]=DEV&tracks[]=DS&tracks[]=QA&types[]=CH&types[]=F2F&types[]=TSK](https://platform.topcoder.com/earn/find/challenges?bucket=Closed%20Challenges&endDateStart=2021-10-04T17:00:00.000Z&page=1&perPage=10&sortBy=updated&totalPrizesFrom=0&totalPrizesTo=10000&tracks[]=DES&tracks[]=DEV&tracks[]=DS&tracks[]=QA&types[]=CH&types[]=F2F&types[]=TSK)<br/>

_**Actual Result(s)**<br/>_
Doesn't have my challenges filter
_**Expected Result(s)**<br/>_
Should have "My Challenges" filter to make the user easily navigate to their challenges like in community app.

_**Screenshot/Screencast**<br/>_
Expected:
![image](/uploads/9dcbc3c428ad9a8e1d5c39efb0169251/image.png)

Actual:
![image](/uploads/1fb6ac8a7688a0d9ea907eb62439ce11/image.png)
<br/>
<br/>
<br/>
**Environment Details**

_**Device(s):**_
Laptop<br/>
_**Operating System:**_
Windows 10 Version 20H2 (OS Build 19042.1237)<br/>
_**Browser:**_
Google Chrome Version 94.0.4606.81 (Official Build) (64-bit)

**Comment by LieutenantRoger** [comment]
Not sure why it's not there originally, but need to discuss with @Oanh

**Comment by Oanh-and-only-Oanh** [comment]
My Challenge bucket in the EARN MFE is not implemented yet. We can leave this as is.
