### ISSUE TITLE
Loading animation not animating

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/micro-frontends-challenges-app#8]
The loading animation in the new MFE challenge details page is not animating properly.

### Current

https://platform.topcoder-dev.com/earn/find/challenges/d4b75f2d-1998-47cf-9c9d-69bcc2d4c474

<img width="1505" alt="Screen_Shot_2021-09-28_at_8_12_04_am" src="https://user-images.githubusercontent.com/21790/134992433-09073061-9230-49f7-a792-0201217122d6.png">

### Existing (and expected)

https://topcoder-dev.com/challenges/d4b75f2d-1998-47cf-9c9d-69bcc2d4c474

**Comment by SathyaJayabal** [comment]
verified on dev

https://user-images.githubusercontent.com/58783823/135045828-bf907370-3449-41ab-b035-242bb38282ba.mov
