### ISSUE TITLE
Width of agreements popup

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/micro-frontends-challenges-app#9]
On dev MFE platform (https://platform.topcoder-dev.com/earn/find/challenges/d4b75f2d-1998-47cf-9c9d-69bcc2d4c474)

Login with `mess` / `appirio123`

Click `Register`

Note that the width of the popup for viewing the agreement text doesn't match the existing site.  We want this to match the existing site.

### Current

<img width="1505" alt="Screen Shot 2021-09-28 at 8 15 20 am" src="https://user-images.githubusercontent.com/21790/134992675-955257ec-db8d-41f2-a929-0aef6004da98.png">

### Existing (and expected)

<img width="1505" alt="Screen Shot 2021-09-28 at 8 15 47 am" src="https://user-images.githubusercontent.com/21790/134992708-8a73fcd0-0c45-40fc-93f9-2f98e8b583b6.png">

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-09-28 at 1 21 41 PM" src="https://user-images.githubusercontent.com/58783823/135046133-bc1bfeb4-8f21-409c-84f6-816b88c0f212.png">
